<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>FreeCAD界面及Python操作入门知识 | 有限元分析与编程</title><meta name="author" content="Xdd"><meta name="copyright" content="Xdd"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="referrer" content="no-referrer"><meta name="description" content="资料官网：https:&#x2F;&#x2F;www.freecad.org&#x2F; Github 仓库：https:&#x2F;&#x2F;github.com&#x2F;FreeCAD&#x2F;FreeCAD 中文文档：https:&#x2F;&#x2F;wiki.freecad.org&#x2F;Online_Help_Toc&#x2F;zh-cn FreeCAD 社区: https:&#x2F;&#x2F;forum.freecad.org&#x2F;index.php?style&#x3D;5 Command Refe">
<meta property="og:type" content="article">
<meta property="og:title" content="FreeCAD界面及Python操作入门知识">
<meta property="og:url" content="https://19970622.xyz/posts/191922/index.html">
<meta property="og:site_name" content="有限元分析与编程">
<meta property="og:description" content="资料官网：https:&#x2F;&#x2F;www.freecad.org&#x2F; Github 仓库：https:&#x2F;&#x2F;github.com&#x2F;FreeCAD&#x2F;FreeCAD 中文文档：https:&#x2F;&#x2F;wiki.freecad.org&#x2F;Online_Help_Toc&#x2F;zh-cn FreeCAD 社区: https:&#x2F;&#x2F;forum.freecad.org&#x2F;index.php?style&#x3D;5 Command Refe">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202408101927182.png">
<meta property="article:published_time" content="2024-09-11T16:00:00.000Z">
<meta property="article:modified_time" content="2024-09-11T16:00:00.000Z">
<meta property="article:author" content="Xdd">
<meta property="article:tag" content="python">
<meta property="article:tag" content="freecad">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202408101927182.png"><link rel="shortcut icon" href="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202310230930281.png"><link rel="canonical" href="https://19970622.xyz/posts/191922/index.html"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="preconnect" href="//busuanzi.ibruce.info"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css" media="print" onload="this.media='all'"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox/fancybox.min.css" media="print" onload="this.media='all'"><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: {"appId":"NQD8RF9R39","apiKey":"3d4e0abab4490c03a3480485272bd1f7","indexName":"blog_hexo","hits":{"per_page":10},"languages":{"input_placeholder":"搜索文章","hits_empty":"找不到您查询的内容：${query}","hits_stats":"找到 ${hits} 条结果，用时 ${time} 毫秒"}},
  localSearch: undefined,
  translate: undefined,
  noticeOutdate: undefined,
  highlight: {"plugin":"highlighjs","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false},
  copy: {
    success: '复制成功',
    error: '复制错误',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '天',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: undefined,
  lightbox: 'fancybox',
  Snackbar: undefined,
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: false,
  percent: {
    toc: true,
    rightside: false,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: 'FreeCAD界面及Python操作入门知识',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  postUpdate: '2024-09-12 00:00:00'
}</script><script>(win=>{
      win.saveToLocal = {
        set: (key, value, ttl) => {
          if (ttl === 0) return
          const now = Date.now()
          const expiry = now + ttl * 86400000
          const item = {
            value,
            expiry
          }
          localStorage.setItem(key, JSON.stringify(item))
        },
      
        get: key => {
          const itemStr = localStorage.getItem(key)
      
          if (!itemStr) {
            return undefined
          }
          const item = JSON.parse(itemStr)
          const now = Date.now()
      
          if (now > item.expiry) {
            localStorage.removeItem(key)
            return undefined
          }
          return item.value
        }
      }
    
      win.getScript = (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        script.onerror = reject
        script.onload = script.onreadystatechange = function() {
          const loadState = this.readyState
          if (loadState && loadState !== 'loaded' && loadState !== 'complete') return
          script.onload = script.onreadystatechange = null
          resolve()
        }

        Object.keys(attr).forEach(key => {
          script.setAttribute(key, attr[key])
        })

        document.head.appendChild(script)
      })
    
      win.getCSS = (url, id = false) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onerror = reject
        link.onload = link.onreadystatechange = function() {
          const loadState = this.readyState
          if (loadState && loadState !== 'loaded' && loadState !== 'complete') return
          link.onload = link.onreadystatechange = null
          resolve()
        }
        document.head.appendChild(link)
      })
    
      win.activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      win.activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }
      const t = saveToLocal.get('theme')
    
        if (t === 'dark') activateDarkMode()
        else if (t === 'light') activateLightMode()
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        if (asideStatus === 'hide') {
          document.documentElement.classList.add('hide-aside')
        } else {
          document.documentElement.classList.remove('hide-aside')
        }
      }
    
      const detectApple = () => {
        if(/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)){
          document.documentElement.classList.add('apple')
        }
      }
      detectApple()
    })(window)</script><link rel="stylesheet" href="/css/font.css"><meta name="generator" content="Hexo 6.3.0"><link rel="alternate" href="/atom.xml" title="有限元分析与编程" type="application/atom+xml">
</head><body><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img is-center"><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202310220936690.jpg" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="sidebar-site-data site-data is-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">72</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">95</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">8</div></a></div><hr class="custom-hr"/><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> 主页</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> 归档</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> 标签</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> 分类</span></a></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-link"></i><span> Link</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" target="_blank" rel="noopener" href="https://flarum.19970622.xyz/"><i class="fa-fw fa-solid fa-share-from-square"></i><span> Flarum</span></a></li><li><a class="site-page child" target="_blank" rel="noopener" href="https://fcb.19970622.xyz/"><i class="fa-fw fa-solid fa-share-from-square"></i><span> FileCodeBox</span></a></li><li><a class="site-page child" target="_blank" rel="noopener" href="http://md.19970622.xyz/"><i class="fa-fw fa-solid fa-share-from-square"></i><span> Doocs/md</span></a></li><li><a class="site-page child" target="_blank" rel="noopener" href="http://demo.19970622.xyz/"><i class="fa-fw fa-solid fa-share-from-square"></i><span> Todo</span></a></li></ul></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg" id="page-header" style="background-image: url('https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202408101927182.png')"><nav id="nav"><span id="blog-info"><a href="/" title="有限元分析与编程"><span class="site-name">有限元分析与编程</span></a></span><div id="menus"><div id="search-button"><a class="site-page social-icon search" href="javascript:void(0);"><i class="fas fa-search fa-fw"></i><span> 搜索</span></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> 主页</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> 归档</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> 标签</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> 分类</span></a></div><div class="menus_item"><a class="site-page group" href="javascript:void(0);"><i class="fa-fw fas fa-link"></i><span> Link</span><i class="fas fa-chevron-down"></i></a><ul class="menus_item_child"><li><a class="site-page child" target="_blank" rel="noopener" href="https://flarum.19970622.xyz/"><i class="fa-fw fa-solid fa-share-from-square"></i><span> Flarum</span></a></li><li><a class="site-page child" target="_blank" rel="noopener" href="https://fcb.19970622.xyz/"><i class="fa-fw fa-solid fa-share-from-square"></i><span> FileCodeBox</span></a></li><li><a class="site-page child" target="_blank" rel="noopener" href="http://md.19970622.xyz/"><i class="fa-fw fa-solid fa-share-from-square"></i><span> Doocs/md</span></a></li><li><a class="site-page child" target="_blank" rel="noopener" href="http://demo.19970622.xyz/"><i class="fa-fw fa-solid fa-share-from-square"></i><span> Todo</span></a></li></ul></div></div><div id="toggle-menu"><a class="site-page" href="javascript:void(0);"><i class="fas fa-bars fa-fw"></i></a></div></div></nav><div id="post-info"><h1 class="post-title">FreeCAD界面及Python操作入门知识</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-09-11T16:00:00.000Z" title="发表于 2024-09-12 00:00:00">2024-09-12</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2024-09-11T16:00:00.000Z" title="更新于 2024-09-12 00:00:00">2024-09-12</time></span><span class="post-meta-categories"><span class="post-meta-separator">|</span><i class="fas fa-inbox fa-fw post-meta-icon"></i><a class="post-meta-categories" href="/categories/CAE/">CAE</a></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title="FreeCAD界面及Python操作入门知识"><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">阅读量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="post-content" id="article-container"><h2 id="资料"><a href="#资料" class="headerlink" title="资料"></a>资料</h2><p>官网：<a target="_blank" rel="noopener" href="https://www.freecad.org/">https://www.freecad.org/</a></p>
<p>Github 仓库：<a target="_blank" rel="noopener" href="https://github.com/FreeCAD/FreeCAD">https://github.com/FreeCAD/FreeCAD</a></p>
<p>中文文档：<a target="_blank" rel="noopener" href="https://wiki.freecad.org/Online_Help_Toc/zh-cn">https://wiki.freecad.org/Online_Help_Toc&#x2F;zh-cn</a></p>
<p>FreeCAD 社区: <a target="_blank" rel="noopener" href="https://forum.freecad.org/index.php?style=5">https://forum.freecad.org/index.php?style=5</a></p>
<p><font style="color:rgb(0, 0, 0);">Command Reference</font>: <a target="_blank" rel="noopener" href="https://wiki.freecad.org/Category:Command_Reference/zh-cn">https://wiki.freecad.org/Category:Command_Reference&#x2F;zh-cn</a></p>
<p><font style="color:rgba(0, 0, 0, 0.9);">FreeCAD|API 及其用法</font>：<a target="_blank" rel="noopener" href="https://mp.weixin.qq.com/s/6yTHeZdN3dIZEHwHGpu8xg">https://mp.weixin.qq.com/s/6yTHeZdN3dIZEHwHGpu8xg</a></p>
<h2 id="鼠标键盘操作"><a href="#鼠标键盘操作" class="headerlink" title="鼠标键盘操作"></a>鼠标键盘操作</h2><p>缩放：滚轮，向下是缩小</p>
<p>移动：Ctrl+右键</p>
<p>旋转：Shift+右键</p>
<h2 id="GUI-操作"><a href="#GUI-操作" class="headerlink" title="GUI 操作"></a>GUI 操作</h2><h3 id="中文界面"><a href="#中文界面" class="headerlink" title="中文界面"></a>中文界面</h3><p>Edit—Preferences—General—Language—简体中文</p>
<h3 id="建立几何-Part"><a href="#建立几何-Part" class="headerlink" title="建立几何-Part"></a>建立几何-Part<img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409131649877.png"></h3><ol>
<li>工作台切换到 Part</li>
<li>零件—创建图元—可以创建：平面，立方体，圆柱体，圆锥体，球体，椭圆体，圆环体，棱柱，楔形，螺旋体，螺旋，圆，椭圆，点，线，正多边形</li>
<li>零件—拉伸</li>
</ol>
<h3 id="建立草图-Sketcher"><a href="#建立草图-Sketcher" class="headerlink" title="建立草图-Sketcher"></a>建立草图-Sketcher</h3><p><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409131652577.png"></p>
<ol>
<li>工作台切换到 Sketcher</li>
<li>Sketcher—创建草图</li>
<li>建立各种线，修剪</li>
<li>建立约束。共点，点在线上，水平，垂直，平行，设置线的水平长度等</li>
<li>退出草图工作台，可以再切换到 Part 工作台进行拉伸</li>
</ol>
<p><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409131638908.png"></p>
<h2 id="Python-操作-FreeCAD"><a href="#Python-操作-FreeCAD" class="headerlink" title="Python 操作 FreeCAD"></a>Python 操作 FreeCAD</h2><blockquote>
<p>文档：<a target="_blank" rel="noopener" href="https://wiki.freecad.org/Manual:A_gentle_introduction">https://wiki.freecad.org/Manual:A_gentle_introduction</a></p>
</blockquote>
<p>打开 Python 面板：View—Panels—Python console</p>
<p>这样，我们在 FreeCAD 中的每一步操作都会有相应的 Python 代码在控制台输出。</p>
<h3 id="官方文档创建-box"><a href="#官方文档创建-box" class="headerlink" title="官方文档创建 box"></a>官方文档创建 box</h3><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># 创建一个新的空文档</span></span><br><span class="line">doc = FreeCAD.newDocument()</span><br><span class="line"></span><br><span class="line"><span class="comment"># 输入doc可在控制台的提示中看到其属性与方法</span></span><br><span class="line"><span class="comment"># 通常以大写字母开头的名称是属性，以小写字母开头的名称是函数</span></span><br><span class="line">doc</span><br><span class="line"></span><br><span class="line"><span class="comment"># 将新对象添加到我们的文档中</span></span><br><span class="line">box = doc.addObject(<span class="string">&quot;Part::Box&quot;</span>,<span class="string">&quot;myBox&quot;</span>)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 使用 Python 时,文档不会自动重新计算。我们必须在需要时手动执行此操作来刷新界面</span></span><br><span class="line"><span class="comment"># doc.recompute() 执行完毕后就可以看到FreeCAD创建了一个立方体</span></span><br><span class="line">doc.recompute()</span><br><span class="line"></span><br><span class="line"><span class="comment"># 获取所有的对象类型的列表</span></span><br><span class="line">doc.supportedTypes()</span><br><span class="line"></span><br><span class="line"><span class="comment"># 探索一下盒子属性</span></span><br><span class="line">box.Height</span><br><span class="line"><span class="comment"># &gt;&gt; 10.0 mm</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 改变盒子的尺寸</span></span><br><span class="line">box.Length=<span class="number">20</span></span><br><span class="line">box.Width = <span class="number">5</span></span><br><span class="line">box.Height = <span class="number">5</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 查看框的线条颜色</span></span><br><span class="line">box.ViewObject.LineColor</span><br><span class="line"></span><br><span class="line"><span class="comment"># 创建矢量-矢量加减</span></span><br><span class="line">myvec = FreeCAD.Vector(<span class="number">2</span>,<span class="number">0</span>,<span class="number">0</span>)</span><br><span class="line">othervec = FreeCAD.Vector(<span class="number">0</span>,<span class="number">3</span>,<span class="number">0</span>)</span><br><span class="line">sumvec = myvec.add(othervec)</span><br><span class="line"><span class="comment"># &gt;&gt; Vector (2.0, 3.0, 0.0)</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># FreeCAD每个对象都有一个 Placement 属性，它包含对象的位置（Base）和方向（Rotation）</span></span><br><span class="line">box.Placement</span><br><span class="line"><span class="comment"># &gt;&gt; Placement [Pos=(0,0,0), Yaw-Pitch-Roll=(0,0,0)]</span></span><br><span class="line">box.Placement.Base</span><br><span class="line"><span class="comment"># &gt;&gt; Vector (0.0, 0.0, 0.0)</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 将box从点box.Placement.Base移动到点sumvec</span></span><br><span class="line">box.Placement.Base = sumvec</span><br><span class="line"></span><br></pre></td></tr></table></figure>

<p><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409122020767.png"></p>
<h3 id="官方文档创建点-线-面-体"><a href="#官方文档创建点-线-面-体" class="headerlink" title="官方文档创建点-线-面-体"></a>官方文档创建点-线-面-体</h3><blockquote>
<p><a target="_blank" rel="noopener" href="https://wiki.freecad.org/Manual:Creating_and_manipulating_geometry">https://wiki.freecad.org/Manual:Creating_and_manipulating_geometry</a></p>
</blockquote>
<p><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409131356169.png"></p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> FreeCAD</span><br><span class="line"><span class="keyword">import</span> Part</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="comment"># 点</span></span><br><span class="line">V1 = FreeCAD.Vector(<span class="number">0</span>,<span class="number">10</span>,<span class="number">0</span>)</span><br><span class="line">V2 = FreeCAD.Vector(<span class="number">30</span>,<span class="number">10</span>,<span class="number">0</span>)</span><br><span class="line">V3 = FreeCAD.Vector(<span class="number">30</span>,-<span class="number">10</span>,<span class="number">0</span>)</span><br><span class="line">V4 = FreeCAD.Vector(<span class="number">0</span>,-<span class="number">10</span>,<span class="number">0</span>)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 线</span></span><br><span class="line">L1 = Part.LineSegment(V1,V2)</span><br><span class="line">L2 = Part.LineSegment(V4,V3)</span><br><span class="line">VC1 = FreeCAD.Vector(-<span class="number">10</span>,<span class="number">0</span>,<span class="number">0</span>)</span><br><span class="line">C1 = Part.Arc(V1,VC1,V4)</span><br><span class="line">VC2 = FreeCAD.Vector(<span class="number">40</span>,<span class="number">0</span>,<span class="number">0</span>)</span><br><span class="line">C2 = Part.Arc(V2,VC2,V3)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 边界</span></span><br><span class="line">E1 = Part.Edge(L1)</span><br><span class="line">E2 = Part.Edge(L2)</span><br><span class="line">E3 = Part.Edge(C1)</span><br><span class="line">E4 = Part.Edge(C2)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 添加几何到文档,几何名称会自动生成;也可以不添加,等形成了几何体,再添加体</span></span><br><span class="line"><span class="comment"># Part.show(E1)</span></span><br><span class="line"><span class="comment"># Part.show(E2)</span></span><br><span class="line"><span class="comment"># Part.show(E3)</span></span><br><span class="line"><span class="comment"># Part.show(E4)</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 曲线</span></span><br><span class="line">W = Part.Wire([E1,E4,E2,E3])</span><br><span class="line"><span class="comment"># 面</span></span><br><span class="line">F = Part.Face(W)</span><br><span class="line"><span class="comment"># 体-拉伸</span></span><br><span class="line">P1 = F.extrude(FreeCAD.Vector(<span class="number">0</span>,<span class="number">0</span>,<span class="number">10</span>))</span><br><span class="line"><span class="built_in">print</span>(P.ShapeType)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 添加几何体到文档</span></span><br><span class="line">obj = FreeCAD.ActiveDocument.addObject(<span class="string">&quot;Part::Feature&quot;</span>,<span class="string">&quot;Solid_1&quot;</span>)</span><br><span class="line">obj.Shape = P1</span><br><span class="line">FreeCAD.ActiveDocument.recompute()</span><br><span class="line"></span><br></pre></td></tr></table></figure>

<h3 id="其他常用操作"><a href="#其他常用操作" class="headerlink" title="其他常用操作"></a>其他常用操作</h3><h4 id="创建几何"><a href="#创建几何" class="headerlink" title="创建几何"></a>创建几何</h4><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br></pre></td><td class="code"><pre><span class="line">创建向量</span><br><span class="line">V1 = App.Vector(<span class="number">0</span>, <span class="number">5</span>, <span class="number">0</span>)</span><br><span class="line"></span><br><span class="line">创建直线</span><br><span class="line">L1 = Part.LineSegment(V1, V2)</span><br><span class="line"></span><br><span class="line">创建圆线</span><br><span class="line">c = Part.makeCircle(<span class="number">5</span>)</span><br><span class="line"></span><br><span class="line">创建圆弧线</span><br><span class="line">c = Part.Arc(V1, VC1, V4)</span><br><span class="line"></span><br><span class="line">创建多边形</span><br><span class="line">V1 = App.Vector(<span class="number">0</span>, <span class="number">2</span>, <span class="number">0</span>)</span><br><span class="line">V2 = App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>)</span><br><span class="line">V3 = App.Vector(<span class="number">2</span>, <span class="number">0</span>, <span class="number">0</span>)</span><br><span class="line">wire = Part.makePolygon([V1, V2, V3，V1])</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">创建边界</span><br><span class="line">edge1 = Part.makeLine((<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>), (<span class="number">2</span>, <span class="number">0</span>, <span class="number">0</span>))</span><br><span class="line">edge2 = Part.makeLine((<span class="number">2</span>, <span class="number">0</span>, <span class="number">0</span>), (<span class="number">2</span>, <span class="number">2</span>, <span class="number">0</span>))</span><br><span class="line">wire = Part.Wire([edge1, edge2])</span><br><span class="line"></span><br><span class="line">创建面</span><br><span class="line">face = Part.Face(wire1)</span><br><span class="line"></span><br><span class="line">创建平面</span><br><span class="line">plane = Part.makePlane(<span class="number">3</span>, <span class="number">3</span>, App.Vector(<span class="number">4</span>, <span class="number">0</span>, <span class="number">0</span>), App.Vector(<span class="number">0</span>, <span class="number">1</span>, <span class="number">0</span>))</span><br><span class="line"></span><br><span class="line">创建椭圆</span><br><span class="line">Part.Ellipse(Center, MajorRadius, MinorRadius)</span><br><span class="line"></span><br><span class="line">创建环面</span><br><span class="line">tor=Part.makeTorus(<span class="number">20</span>, <span class="number">10</span>, App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>), App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>), <span class="number">0</span>, <span class="number">360</span>, <span class="number">180</span>)</span><br><span class="line"></span><br><span class="line">创建长方体</span><br><span class="line">box = Part.makeBox(<span class="number">10</span>, <span class="number">10</span>, <span class="number">10</span>)</span><br><span class="line"></span><br><span class="line">创建球体</span><br><span class="line">sphere1 = Part.makeSphere(<span class="number">5</span>)</span><br><span class="line">sphere2 = Part.makeSphere(<span class="number">5</span>, App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>), App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>), -<span class="number">90</span>, <span class="number">90</span>, <span class="number">180</span>)</span><br><span class="line"></span><br><span class="line">创建圆柱</span><br><span class="line">cylinder1 = Part.makeCylinder(<span class="number">4</span>, <span class="number">10</span>)</span><br><span class="line">cylinder2 = Part.makeCylinder(<span class="number">4</span>, <span class="number">10</span>, App.Vector(<span class="number">20</span>, <span class="number">0</span>, <span class="number">0</span>), App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>), <span class="number">180</span>)</span><br><span class="line"></span><br><span class="line">创建圆锥</span><br><span class="line">cone1 = Part.makeCone(<span class="number">5</span>, <span class="number">0</span>, <span class="number">20</span>)</span><br><span class="line">cone2 = Part.makeCone(<span class="number">5</span>, <span class="number">0</span>, <span class="number">20</span>, App.Vector(<span class="number">20</span>, <span class="number">0</span>, <span class="number">0</span>), App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>), <span class="number">180</span>)</span><br><span class="line"></span><br></pre></td></tr></table></figure>

<h4 id="布尔操作"><a href="#布尔操作" class="headerlink" title="布尔操作"></a>布尔操作</h4><blockquote>
<p>合并 fuse，减 cut，相交 common</p>
</blockquote>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> FreeCAD <span class="keyword">as</span> App</span><br><span class="line"><span class="keyword">import</span> Part</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="comment"># 布尔减</span></span><br><span class="line">cylinder = Part.makeCylinder(<span class="number">3</span>, <span class="number">10</span>, App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>), App.Vector(<span class="number">1</span>, <span class="number">0</span>, <span class="number">0</span>))</span><br><span class="line"><span class="comment"># Part.show(cylinder)</span></span><br><span class="line"></span><br><span class="line">sphere = Part.makeSphere(<span class="number">5</span>, App.Vector(<span class="number">5</span>, <span class="number">0</span>, <span class="number">0</span>))</span><br><span class="line"><span class="comment"># Part.show(sphere)</span></span><br><span class="line"></span><br><span class="line">diff = cylinder.cut(sphere)</span><br><span class="line">Part.show(diff)</span><br><span class="line"></span><br><span class="line"><span class="comment"># Part.show(diff.Solids[0])</span></span><br></pre></td></tr></table></figure>

<p><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409131401397.png"></p>
<h4 id="平移"><a href="#平移" class="headerlink" title="平移"></a>平移</h4><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> FreeCAD <span class="keyword">as</span> App</span><br><span class="line"></span><br><span class="line">myShape = Part.makeBox(<span class="number">2</span>, <span class="number">2</span>, <span class="number">2</span>)</span><br><span class="line">Part.show(myShape)</span><br><span class="line">myShape.Placement</span><br><span class="line"><span class="comment"># &gt;&gt; Placement [Pos=(0,0,0), Yaw-Pitch-Roll=(0,0,0)]</span></span><br><span class="line"></span><br><span class="line">myShape.translate(App.Vector(<span class="number">10</span>, <span class="number">0</span>, <span class="number">0</span>))</span><br><span class="line">Part.show(myShape)</span><br><span class="line">myShape.Placement</span><br><span class="line"><span class="comment"># &gt;&gt; Placement [Pos=(10,0,0), Yaw-Pitch-Roll=(0,0,0)]</span></span><br><span class="line"></span><br></pre></td></tr></table></figure>

<p><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409131416318.png"></p>
<h4 id="旋转"><a href="#旋转" class="headerlink" title="旋转"></a>旋转</h4><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> FreeCAD <span class="keyword">as</span> App</span><br><span class="line"></span><br><span class="line">myShape = Part.makeBox(<span class="number">2</span>, <span class="number">2</span>, <span class="number">2</span>)</span><br><span class="line">Part.show(myShape)</span><br><span class="line">myShape.Placement</span><br><span class="line"><span class="comment"># &gt;&gt; Placement [Pos=(0,0,0), Yaw-Pitch-Roll=(0,0,0)]</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 绕直线(0,0,0)-(0,0,1)旋转180°</span></span><br><span class="line">myShape.rotate(App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>),App.Vector(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>), <span class="number">180</span>)</span><br><span class="line">Part.show(myShape)</span><br><span class="line">myShape.Placement</span><br><span class="line"><span class="comment"># &gt;&gt; Placement [Pos=(0,0,0), Yaw-Pitch-Roll=(180,0,0)]</span></span><br><span class="line"></span><br></pre></td></tr></table></figure>

<p><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409131417914.png"></p>
<h4 id="矩阵变换与缩放"><a href="#矩阵变换与缩放" class="headerlink" title="矩阵变换与缩放"></a>矩阵变换与缩放</h4><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># 矩阵变换</span></span><br><span class="line">myMat = App.Matrix()</span><br><span class="line">myMat.move(App.Vector(<span class="number">2</span>, <span class="number">0</span>, <span class="number">0</span>))</span><br><span class="line">myMat.rotateZ(math.pi/<span class="number">2</span>)</span><br><span class="line">myShape.transformShape(myMat)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 缩放</span></span><br><span class="line">myMat = App.Matrix()</span><br><span class="line">myMat.scale(<span class="number">2</span>, <span class="number">1</span>, <span class="number">1</span>)</span><br><span class="line">myShape=myShape.transformGeometry(myMat)</span><br></pre></td></tr></table></figure>

<h4 id="导入-stp-文件"><a href="#导入-stp-文件" class="headerlink" title="导入 stp 文件"></a>导入 stp 文件</h4><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> Part</span><br><span class="line">shape = Part.Shape()</span><br><span class="line">shape.read(<span class="string">&quot;your_file_path&quot;</span>)</span><br><span class="line">shape</span><br></pre></td></tr></table></figure>

<h3 id="界面制作"><a href="#界面制作" class="headerlink" title="界面制作"></a>界面制作</h3><p><a target="_blank" rel="noopener" href="https://www.yuque.com/xdd1997/ek3kug/xk5xu4?singleDoc#">https://www.yuque.com/xdd1997/ek3kug/xk5xu4?singleDoc#</a> 《FreeCAD 笔记》</p>
</article><div class="post-copyright"><div class="post-copyright__author"><span class="post-copyright-meta"><i class="fas fa-circle-user fa-fw"></i>文章作者: </span><span class="post-copyright-info"><a href="https://19970622.xyz">Xdd</a></span></div><div class="post-copyright__type"><span class="post-copyright-meta"><i class="fas fa-square-arrow-up-right fa-fw"></i>文章链接: </span><span class="post-copyright-info"><a href="https://19970622.xyz/posts/191922/">https://19970622.xyz/posts/191922/</a></span></div><div class="post-copyright__notice"><span class="post-copyright-meta"><i class="fas fa-circle-exclamation fa-fw"></i>版权声明: </span><span class="post-copyright-info">本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a> 许可协议。转载请注明来自 <a href="https://19970622.xyz" target="_blank">有限元分析与编程</a>！</span></div></div><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/python/">python</a><a class="post-meta__tags" href="/tags/freecad/">freecad</a></div><div class="post_share"><div class="social-share" data-image="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202408101927182.png" data-sites="wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><div class="post-reward"><div class="reward-button"><i class="fas fa-qrcode"></i>赞助</div><div class="reward-main"><ul class="reward-all"><li class="reward-item"><a href="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202310220956863.png" target="_blank"><img class="post-qr-code-img" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202310220956863.png" alt="wechat"/></a><div class="post-qr-code-desc">wechat</div></li><li class="reward-item"><a href="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202310220956689.png" target="_blank"><img class="post-qr-code-img" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202310220956689.png" alt="alipay"/></a><div class="post-qr-code-desc">alipay</div></li></ul></div></div><nav class="pagination-post" id="pagination"><div class="prev-post pull-left"><a href="/posts/10181029/" title="Tecplot数据格式"><img class="cover" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202408101928798.png" onerror="onerror=null;src='/img/404.jpg'" alt="cover of previous post"><div class="pagination-info"><div class="label">上一篇</div><div class="prev_info">Tecplot数据格式</div></div></a></div><div class="next-post pull-right"><a href="/posts/104026/" title="HyperMesh-Python-API"><img class="cover" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409112117869.jpg" onerror="onerror=null;src='/img/404.jpg'" alt="cover of next post"><div class="pagination-info"><div class="label">下一篇</div><div class="next_info">HyperMesh-Python-API</div></div></a></div></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><div><a href="/posts/250828/" title="1panel+python+flask"><img class="cover" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202508282004773.png" alt="cover"><div class="content is-center"><div class="date"><i class="far fa-calendar-alt fa-fw"></i> 2025-08-28</div><div class="title">1panel+python+flask</div></div></a></div><div><a href="/posts/8412/" title="Anaconda新建并使用新环境"><img class="cover" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202310231638488.png" alt="cover"><div class="content is-center"><div class="date"><i class="far fa-calendar-alt fa-fw"></i> 2023-10-23</div><div class="title">Anaconda新建并使用新环境</div></div></a></div><div><a href="/posts/104026/" title="HyperMesh-Python-API"><img class="cover" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202409112117869.jpg" alt="cover"><div class="content is-center"><div class="date"><i class="far fa-calendar-alt fa-fw"></i> 2024-09-11</div><div class="title">HyperMesh-Python-API</div></div></a></div><div><a href="/posts/1043/" title="PySide6的入门配置"><img class="cover" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202403291056730.jpg" alt="cover"><div class="content is-center"><div class="date"><i class="far fa-calendar-alt fa-fw"></i> 2024-04-12</div><div class="title">PySide6的入门配置</div></div></a></div><div><a href="/posts/142701/" title="PyQt的线程类QThread与计时器类Qtimer"><img class="cover" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202408101927152.png" alt="cover"><div class="content is-center"><div class="date"><i class="far fa-calendar-alt fa-fw"></i> 2024-09-08</div><div class="title">PyQt的线程类QThread与计时器类Qtimer</div></div></a></div><div><a href="/posts/3180/" title="Pycharm如何使用某一个Python的环境"><img class="cover" src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202403291058206.jpg" alt="cover"><div class="content is-center"><div class="date"><i class="far fa-calendar-alt fa-fw"></i> 2024-03-20</div><div class="title">Pycharm如何使用某一个Python的环境</div></div></a></div></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info"><div class="is-center"><div class="avatar-img"><img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202310220936690.jpg" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info__name">Xdd</div><div class="author-info__description">为往圣继绝学</div></div><div class="card-info-data site-data is-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">72</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">95</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">8</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/xie-dd"><i class="fab fa-github"></i><span>Follow Me</span></a></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content"><center><b>--- 联系方式 ---<br><font color="#5ea6e5">xdd2026@qq.com</font></b></center></div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E8%B5%84%E6%96%99"><span class="toc-number">1.</span> <span class="toc-text">资料</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E9%BC%A0%E6%A0%87%E9%94%AE%E7%9B%98%E6%93%8D%E4%BD%9C"><span class="toc-number">2.</span> <span class="toc-text">鼠标键盘操作</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#GUI-%E6%93%8D%E4%BD%9C"><span class="toc-number">3.</span> <span class="toc-text">GUI 操作</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E4%B8%AD%E6%96%87%E7%95%8C%E9%9D%A2"><span class="toc-number">3.1.</span> <span class="toc-text">中文界面</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%BB%BA%E7%AB%8B%E5%87%A0%E4%BD%95-Part"><span class="toc-number">3.2.</span> <span class="toc-text">建立几何-Part</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%BB%BA%E7%AB%8B%E8%8D%89%E5%9B%BE-Sketcher"><span class="toc-number">3.3.</span> <span class="toc-text">建立草图-Sketcher</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Python-%E6%93%8D%E4%BD%9C-FreeCAD"><span class="toc-number">4.</span> <span class="toc-text">Python 操作 FreeCAD</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E5%88%9B%E5%BB%BA-box"><span class="toc-number">4.1.</span> <span class="toc-text">官方文档创建 box</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E5%88%9B%E5%BB%BA%E7%82%B9-%E7%BA%BF-%E9%9D%A2-%E4%BD%93"><span class="toc-number">4.2.</span> <span class="toc-text">官方文档创建点-线-面-体</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%85%B6%E4%BB%96%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C"><span class="toc-number">4.3.</span> <span class="toc-text">其他常用操作</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%88%9B%E5%BB%BA%E5%87%A0%E4%BD%95"><span class="toc-number">4.3.1.</span> <span class="toc-text">创建几何</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%B8%83%E5%B0%94%E6%93%8D%E4%BD%9C"><span class="toc-number">4.3.2.</span> <span class="toc-text">布尔操作</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%B9%B3%E7%A7%BB"><span class="toc-number">4.3.3.</span> <span class="toc-text">平移</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E6%97%8B%E8%BD%AC"><span class="toc-number">4.3.4.</span> <span class="toc-text">旋转</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E7%9F%A9%E9%98%B5%E5%8F%98%E6%8D%A2%E4%B8%8E%E7%BC%A9%E6%94%BE"><span class="toc-number">4.3.5.</span> <span class="toc-text">矩阵变换与缩放</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#%E5%AF%BC%E5%85%A5-stp-%E6%96%87%E4%BB%B6"><span class="toc-number">4.3.6.</span> <span class="toc-text">导入 stp 文件</span></a></li></ol></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E7%95%8C%E9%9D%A2%E5%88%B6%E4%BD%9C"><span class="toc-number">4.4.</span> <span class="toc-text">界面制作</span></a></li></ol></li></ol></div></div></div></div></main><footer id="footer"><div id="footer-wrap"><div class="copyright">&copy;2023 - 2025 By Xdd</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a><span> | 豫ICP备<a href="https://beian.miit.gov.cn/" target="_blank">2023031381</a>号</span>
<span> | <img src="https://mypic2016.oss-cn-beijing.aliyuncs.com/picGo/202311231912584.png" height="16" width="16" style="display:inline-block;"> 豫公网安备<a href="https://beian.mps.gov.cn/#/query/webSearch?code=41140002000710\" target="_blank">41140002000710</a>号</span></div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="浅色和深色模式转换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="直达评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox/fancybox.umd.min.js"></script><div class="js-pjax"><script>(()=>{
  const getGiscusTheme = theme => {
    return theme === 'dark' ? 'dark' : 'light'
  }

  const loadGiscus = () => {
    const config = Object.assign({
      src: 'https://giscus.app/client.js',
      'data-repo': 'xie-dd/blog_hexo_comment',
      'data-repo-id': 'R_kgDOKjyVRg',
      'data-category-id': 'DIC_kwDOKjyVRs4Car4o',
      'data-mapping': 'pathname',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true
    },null)

    const ele = document.createElement('script')
    for (let key in config) {
      ele.setAttribute(key, config[key])
    }
    document.getElementById('giscus-wrap').appendChild(ele)
  }

  const changeGiscusTheme = theme => {
    const sendMessage = message => {
      const iframe = document.querySelector('iframe.giscus-frame')
      if (!iframe) return
      iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app')
    }

    sendMessage({
      setConfig: {
        theme: getGiscusTheme(theme)
      }
    });
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment= loadGiscus
  }
})()</script></div><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="algolia-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="search-wrap"><div id="algolia-search-input"></div><hr/><div id="algolia-search-results"><div id="algolia-hits"></div><div id="algolia-pagination"></div><div id="algolia-info"><div class="algolia-stats"></div><div class="algolia-poweredBy"></div></div></div></div></div><div id="search-mask"></div><script src="https://cdn.jsdelivr.net/npm/algoliasearch/dist/algoliasearch-lite.umd.min.js"></script><script src="https://cdn.jsdelivr.net/npm/instantsearch.js/dist/instantsearch.production.min.js"></script><script src="/js/search/algolia.js"></script></div></div></body></html>